-- Wrap auth/session function calls in RLS policy predicates in (SELECT ...) so Postgres
-- evaluates them once per statement (InitPlan) instead of once per row -- the
-- Supabase-documented RLS perf pattern. Predicate-equivalent (row visibility unchanged).
-- Generated by 'pgrls fix --rule PERF001' and verified (PERF001 -> 0). Refs #81.

-- [PERF001] Wrap auth function call(s) in policy 'devices_api_key_select_policy' on public.devices so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY devices_api_key_select_policy ON public.devices
    USING ((SELECT current_setting(CAST('app.device_api_key' AS text), TRUE)) <> CAST('' AS text) AND CAST(api_key AS text) = (SELECT current_setting(CAST('app.device_api_key' AS text), TRUE)));

-- [PERF001] Wrap auth function call(s) in policy 'devices_delete_policy' on public.devices so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY devices_delete_policy ON public.devices
    USING (user_id = (SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)));

-- [PERF001] Wrap auth function call(s) in policy 'devices_select_policy' on public.devices so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY devices_select_policy ON public.devices
    USING (user_id = (SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)) OR user_id IS NULL);

-- [PERF001] Wrap auth function call(s) in policy 'devices_update_policy' on public.devices so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY devices_update_policy ON public.devices
    USING (user_id = (SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)));

-- [PERF001] Wrap auth function call(s) in policy 'mixups_delete_policy' on public.mixups so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY mixups_delete_policy ON public.mixups
    USING (user_id = (SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)));

-- [PERF001] Wrap auth function call(s) in policy 'mixups_select_policy' on public.mixups so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY mixups_select_policy ON public.mixups
    USING (user_id = (SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)) OR user_id IS NULL);

-- [PERF001] Wrap auth function call(s) in policy 'mixups_update_policy' on public.mixups so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY mixups_update_policy ON public.mixups
    USING (user_id = (SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)));

-- [PERF001] Wrap auth function call(s) in policy 'playlists_delete_policy' on public.playlists so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY playlists_delete_policy ON public.playlists
    USING (user_id = (SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)));

-- [PERF001] Wrap auth function call(s) in policy 'playlists_select_policy' on public.playlists so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY playlists_select_policy ON public.playlists
    USING (user_id = (SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)) OR user_id IS NULL);

-- [PERF001] Wrap auth function call(s) in policy 'playlists_update_policy' on public.playlists so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY playlists_update_policy ON public.playlists
    USING (user_id = (SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)));

-- [PERF001] Wrap auth function call(s) in policy 'plugin_settings_capability_select_policy' on public.plugin_settings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY plugin_settings_capability_select_policy ON public.plugin_settings
    USING ((SELECT current_setting(CAST('app.capability_lookup_uuid' AS text), TRUE)) <> CAST('' AS text) AND uuid = (SELECT current_setting(CAST('app.capability_lookup_uuid' AS text), TRUE)));

-- [PERF001] Wrap auth function call(s) in policy 'plugin_settings_delete_policy' on public.plugin_settings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY plugin_settings_delete_policy ON public.plugin_settings
    USING (user_id = (SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)));

-- [PERF001] Wrap auth function call(s) in policy 'plugin_settings_select_policy' on public.plugin_settings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY plugin_settings_select_policy ON public.plugin_settings
    USING (user_id = (SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)));

-- [PERF001] Wrap auth function call(s) in policy 'plugin_settings_update_policy' on public.plugin_settings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY plugin_settings_update_policy ON public.plugin_settings
    USING (user_id = (SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)));

-- [PERF001] Wrap auth function call(s) in policy 'recipes_delete_policy' on public.recipes so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY recipes_delete_policy ON public.recipes
    USING (user_id = (SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)));

-- [PERF001] Wrap auth function call(s) in policy 'recipes_select_policy' on public.recipes so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY recipes_select_policy ON public.recipes
    USING (user_id = (SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)) OR user_id IS NULL);

-- [PERF001] Wrap auth function call(s) in policy 'recipes_shared_seed_update_policy' on public.recipes so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY recipes_shared_seed_update_policy ON public.recipes
    USING (user_id IS NULL AND (SELECT current_setting(CAST('app.shared_recipe_seed' AS text), TRUE)) = CAST('on' AS text));

-- [PERF001] Wrap auth function call(s) in policy 'recipes_update_policy' on public.recipes so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY recipes_update_policy ON public.recipes
    USING (user_id = (SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)));

-- [PERF001] Wrap auth function call(s) in policy 'screen_configs_delete_policy' on public.screen_configs so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY screen_configs_delete_policy ON public.screen_configs
    USING (user_id = (SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)));

-- [PERF001] Wrap auth function call(s) in policy 'screen_configs_select_policy' on public.screen_configs so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY screen_configs_select_policy ON public.screen_configs
    USING (user_id = (SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)) OR user_id IS NULL);

-- [PERF001] Wrap auth function call(s) in policy 'screen_configs_update_policy' on public.screen_configs so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY screen_configs_update_policy ON public.screen_configs
    USING (user_id = (SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)));
